// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMinecraftVersion():Promise<string>;

export function PerformInjection(arg1:string):Promise<{[key: string]: any}>;

export function SelectDLL():Promise<string>;
