// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMinecraftVersion() {
  return window['go']['main']['App']['GetMinecraftVersion']();
}

export function PerformInjection(arg1) {
  return window['go']['main']['App']['PerformInjection'](arg1);
}

export function SelectDLL() {
  return window['go']['main']['App']['SelectDLL']();
}
